name: EcoHabits CI & SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud:
    name: Build, Test & Analyze
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout Code (Fetch depth 0 is required for SonarCloud)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Setup Java (Required for SonarScanner)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 5. Run Static Analysis (Linter)
      - name: Run Flutter Analyze
        run: flutter analyze

      # 6. Run Tests with Coverage (PENTING untuk SonarQube)
      - name: Run Tests with Coverage
        run: flutter test --coverage

      # 7. SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Otomatis dari GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Yang kita buat tadi